### ISSUE TITLE
[BUG] How to fix traveler male use the constellation pictures of traveler female ？

### ISSUE THREAD

**Issue by RX6800Super** [Penelopeep/SwitchElementTraveller#10]
This BUG only show on Release v3 and in the Dendro element. I am not sure this BUG will show on other Release.

Release v4 and Release v5，these versions is hard to use，the command of constellation is harduse，and it can not save the constellation data.

I want when I get the 6 constellation of traveler with each element first time，the data will be saved，and when i change element，it is always 6 constellation.

So Release v3 is simple and speedy for me，but it has this BUG.

I want to Fix this BUG for my obsession，and prepare for Genshin4.0 with Hydro element.

Thanks！

**Comment by Penelopeep** [comment]
Hi, what do you mean by:
> these versions is hard to use，the command of constellation is harduse

Also can you send some screenshot of this bug, it's hard for me to say what's causing it
> So Release v3 is simple and speedy for me

Do you have problems with other versions being slow? I never noticed any difference.
> and prepare for Genshin4.0 with Hydro element.

I fixed it in one of updates, it should (and I really mean **should**) work with every element

**Comment by RX6800Super** [comment]
This is the BUG for Release v3，I play in grasscutter for Genshin3.3 Global

First is correct constellation pictures for geo element.

Traveler female
![00](https://user-images.githubusercontent.com/109947312/211594791-2e1d8d34-ef7a-4eb1-8e16-60b6a279ec3a.jpg)

Traveler male
![01](https://user-images.githubusercontent.com/109947312/211594942-69082ae2-82a7-4a8e-bd6d-82a50f33a52b.jpg)

It is left-right symmetry.

And these is the BUG for dendro element.

Traveler female
![02](https://user-images.githubusercontent.com/109947312/211595754-72ace968-c6de-49b0-9135-6f78de12e1e0.jpg)

Traveler male
![03](https://user-images.githubusercontent.com/109947312/211595805-2f8a2c7b-a884-4ee5-aab9-6d8fbfdadb02.jpg)

It is same constellation pictures.

**Comment by RX6800Super** [comment]
For Release v5，it needs input the constellation command，like "/se geo 6" or ”/se grass 6“ to get a 6 constellation Traveler.

When you input without constellation command，like "/se geo" or ”/se grass“，you will get a 0 constellation Traveler.

I dont like this，I like Release v3 which can save the constellation data.  It is handy to change without constellation command.

And I like collecting all element 6 constellation.

(To my visual angle，only Bennett need to change constellation to get 5 or 6 constellation, because it will influence teammate choise.)

For Release v4，the Server can not discern the switch element command，and when you input in GrasscutterControl，it maybe work，but you need to restart the game to switch element success，it doesnt like Release v3 or v5 switch element
immediately.

It is hassle so I will kick Release v4 out.

**Comment by Penelopeep** [comment]
Okay so the thing is:
- This constellation big is probably caused by wrong skilldepot id which I changed few times throughout 2.8.5 beta
- You can download source and remove every call for constellation handler so you shouldn't have a problem with running it without choosing constellations. Fun fact it was also made for 2.8.5 beta when constellations were bugged and this was only in-game option to enable them
- As for this "sometimes works, sometimes not"  I don't remember having this trouble (but I worked on this plugin 3 mo ago, so maybe something changed). May I ask what GC version are you using?

**Comment by RX6800Super** [comment]
I get it，and I will try this.

I use these GC version for these GenshinImapact Global version.

GC v1.3.0 (https://github.com/Grasscutters/Grasscutter/releases/tag/v1.3.0) for GenshinImapct (2.8 / 2.8.5X / 3.0 / 3.0.5X)

GC v1.3.0 (https://github.com/Grasscutters/Grasscutter/releases/tag/v1.4.0) for GenshinImapct (3.1)

GC v1.4.3 (https://github.com/Grasscutters/Grasscutter/releases/tag/v1.4.3) for GenshinImapct (3.1.5X / 3.2)

GC v1.4.4-dev (From others dev version) for GenshinImapct (3.3 / 3.3.5X)

**Comment by RX6800Super** [comment]
My Friends teach me use command.java to set switch element in GC control.

I try it success，the constellation pictures BUG is done， but it also have a fun BUG like your earlier plugin works.

When the player change two different elements For traveler twins，one of them can not charge the elemental burst skill.

Last time I saw this BUG is in GenshinImapact 2.8.5X，when you first do this plugin works，LOL~

Also I test，the plugin commands is high level running than GC commands，the plugin is high level than compile commands.

Buy the way，how can I compile your plugin？I can compile the GC version in my computers but i can not do for your works，
I have no study for Java，I just use few English knowledge to find the files meaning. May be I am stupid.

Can you build a plugin version like what you suggest when you are free? Also I can wait for GenshinImapact 4.0，when we get Hydro element，this BUG may be done.

**Comment by Penelopeep** [comment]
Oh yeah... Of course I forgot to reply. I'm sorry.
However, answering your question:
- How to compile my plugin?
- You have to install maven (it's different on each platform) and use maven package on terminal. Alternatively you can use something like Intellij IDEA which have maven included.

I can make this plugin for you but I don't have much time rn so I can make it probably tomorrow (it would be 21.01)

**Comment by RX6800Super** [comment]
No matter.
I can wait it，thanks you！

**Comment by Penelopeep** [comment]
Try this and check if it's what you wanted
https://cdn.discordapp.com/attachments/922942444671205437/1066528099451293759/Switchelement-1.jar

**Comment by RX6800Super** [comment]
I check it and this version have a UI question in game，and a skill point question.

These are pictures for skill point question，when you change element from you log into game，like change Wind to Grass，the E or Q skill point for 6 constellation Traveler is 10，not 13.

And when you restart the game，the E or Q skill point for Grass element will become right point 13 and you will also get skill point 10 if you change Grass to Wind.

![3](https://user-images.githubusercontent.com/109947312/214059890-625e10e3-fc14-4a21-9f03-ea29570b0052.jpg)

![4](https://user-images.githubusercontent.com/109947312/214059925-e3b544bf-6e97-4abe-a5de-944e44644962.jpg)

![6](https://user-images.githubusercontent.com/109947312/214059969-2bbb7593-9e82-4449-a614-b6e54ac9a03a.jpg)

![8](https://user-images.githubusercontent.com/109947312/214060004-7e3e8949-b0c6-4104-8220-77901d5e15c8.jpg)

Constellation pictures is fixed，thanks you very much!

![5](https://user-images.githubusercontent.com/109947312/214060253-6cb97a6e-5f8f-41bf-af18-497a0cd3243b.jpg)

![7](https://user-images.githubusercontent.com/109947312/214060271-3ee39251-2844-43de-892e-ac419901d24b.jpg)

These are pictures for UI question in game，this question is found when I restart the game and test skill point question.

When you change the element and restart the game，you can not use enterket to get a talk，you should press ESCkey to open your Friend-UI-key to get a talk with grasscutter server.

![0](https://user-images.githubusercontent.com/109947312/214062186-fa5589ca-3aaa-451c-96d9-c5dc3116a9a9.jpg)

![1](https://user-images.githubusercontent.com/109947312/214062208-4ebff3ac-d657-492c-aa91-2a17b6248a3f.jpg)

![2](https://user-images.githubusercontent.com/109947312/214062222-467fe24c-3d12-47a3-9cde-89c5b21d4bb0.jpg)

I test by these version:  Grasscutter-1.4.3 with GenshinImapct 3.2，Grasscutter-1.4.6 with GenshinImapct 3.3.

**Comment by RX6800Super** [comment]
Tips，in this pictures，you can not press key to add talk，it will show you  have no friends to talk.
You need to use ESCkey and touch Friend-UI-key to get a server talk.
I use red pen to circle it.

![0](https://user-images.githubusercontent.com/109947312/214063827-25ffce4a-2044-4174-ad0a-150b13ddf1c2.jpg)

**Comment by Penelopeep** [comment]
I'm sorry if it offend you but I cannot understand your messages. I'm assuming your native language is Chinese and I can understand that you're using translator (or your English isn't that good).
Nonetheless can I ask you to just write it in Chinese or try to form this differently?

**Comment by RX6800Super** [comment]
OK I change to English UI

**Comment by Penelopeep** [comment]
Okay, you don't have to, I get it now.
I have no idea why talent level doesn't update.
I have a theory why it's happening however I can't guarantee anything. I'll try to change it, If that doesn't help then I have no idea

**Comment by Penelopeep** [comment]
Okay, you don't have to, I get it now.
I have no idea why talent level doesn't update.
I have a theory why it's happening however I can't guarantee anything. I'll try to change it, If that doesn't help then I have no idea

**Comment by RX6800Super** [comment]
Oh，its a small problem than earlier version or compile Grasscutter switch command.

I am sorry for my bad English.

It is really hard to fix a BUG without creating some new BUGs.

**Comment by Penelopeep** [comment]
This should fix error with constellations:
https://cdn.discordapp.com/attachments/922906895155621949/1067105307236499528/Switchelement-1.jar
If not then I don't know how to fix constellations.
Also this "bug" with missing chat with server is not caused by my plugin, it's just how gc works.

You can always use my commands from server console 😉

**Comment by RX6800Super** [comment]
I test it，skill point problem is over.

And UI problem is little，we can ignore it because it doesn't influence the game running.

(I guess this problem is between in Grasscutter's code)

Also I suggest you release this version as v3.1.

Thanks！

**Comment by Penelopeep** [comment]
I should make few changes before releasing new version, but I don't have any reason to do so.
I guess you'll have to wait for Fontaine for new update.
However as is it right now it should work up to Snezhnaya with cryo traveller.

**Comment by RX6800Super** [comment]
OK，so the problem is over，I will close this issue.
